### ISSUE TITLE
Rename extension

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-node-editing#33]
Rename it from "cytoscape.js-node-resize" to "cytoscape.js-node-editing" as it already covers non-resize related functionality (move by arrows). README has already been revised to reflect this change.

**Comment by msalihaltun** [comment]
The source files for this extension have now been edited to reflect the new name. The extension can be deprecated and released under a new repository name after a final release under the current name.

**Comment by msalihaltun** [comment]
Name change is currently reflected in [newt:unstable](https://github.com/iVis-at-Bilkent/newt/tree/unstable) except in the package file where the repository link will need to change after the repository name changes.

**Comment by msalihaltun** [comment]
Also reflected in [sbgnviz.js:unstable](https://github.com/iVis-at-Bilkent/sbgnviz.js/tree/unstable) now.

**Comment by msalihaltun** [comment]
[The old package](https://www.npmjs.com/package/cytoscape-node-resize) has now been deprecated in favor of [cytoscape.js-node-editing](https://www.npmjs.com/package/cytoscape-node-editing). [newt:unstable](https://github.com/iVis-at-Bilkent/newt/tree/unstable) has the link to the newly named repository(at unstable) as well. Demo links have also been updated.
