### ISSUE TITLE
Undo of compound node resize to content changes children position

### ISSUE THREAD

**Issue by msalihaltun** [iVis-at-Bilkent/cytoscape.js-node-editing#36]
Resizing a compound node, then resizing it to content, then using undo will cause the compound node and its children to move, next undo will resize the node back. Not sure of the specifics/reproducing yet.

Also see: iVis-at-Bilkent/newt#632, #36. Probably related.

**Comment by ugurdogrusoz** [comment]
@msalihaltun Is this bug reproducable in the undoable demo of this extension?

**Comment by msalihaltun** [comment]
It requires a small bit of modification to make compound nodes resizable in the undoable demo, but it is reproducible.

**Comment by ugurdogrusoz** [comment]
Let's add an option to the demo to make compounds resizable. This should help with debugging as well.

**Comment by msalihaltun** [comment]
Closing now since it seems this particular issue is solved. Looks like it wasn't related to iVis-at-Bilkent/newt#632 or #36.

**Comment by msalihaltun** [comment]
@hasanbalci can you please verify that it works correctly?

**Comment by hasanbalci** [comment]
I'm not sure this is exactly related to this issue, but the following undo operation doesn't work as expected. 
- Resize simple node
- Click on resize to content cue in compound node
- Undo twice and see compound node remains larger and doesn't turn back to its initial size. 
![Peek 2020-10-23 16-13](https://user-images.githubusercontent.com/22586369/97008029-f826fd00-154a-11eb-94e7-190ef0f6d9a6.gif)

**Comment by msalihaltun** [comment]
It was unrelated, but should be fixed now. Can you please test again @hasanbalci?

**Comment by hasanbalci** [comment]
It seems there is no problem now, so closing.
