### ISSUE TITLE
Clicking resize to content cue multiple times locks compound node resize handles

### ISSUE THREAD

**Issue by msalihaltun** [iVis-at-Bilkent/cytoscape.js-node-editing#37]
Not a very consistent bug but when compound node resize cues are clicked a few times, it seems they can't be resized anymore.

Possibly related to: #36, iVis-at-Bilkent/newt#632

**Comment by ugurdogrusoz** [comment]
@msalihaltun Ideally, once you resize a node to its content, the Resize to content cue should disappear since it's not applicable but we might have never truly achieved this for compound nodes in the past.

**Comment by msalihaltun** [comment]
It seems like the extension doesn't make the cue disappear at all. The current functionality will unselect the node after resizing to content which will make all cues/handles disappear but when the unselect call is not present I can see that the cue is not disappearing.

**Comment by ugurdogrusoz** [comment]
Maybe not rendering the visual cue when the node is already sized to the content is something we implemented in Newt (you may observe this behavior easily with simple nodes in Newt)?

**Comment by msalihaltun** [comment]
Yes, Newt functions in that way, there is an explicit call after resize to content operation to clear the visual cue.

**Comment by hasanbalci** [comment]
I'm not sure this is exactly related to this issue, but the following undo operation doesn't work as expected. 
- Resize simple node
- Click on resize to content cue in compound node
- Undo twice and see compound node remains larger and doesn't turn back to its initial size. 
![Peek 2020-10-23 16-13](https://user-images.githubusercontent.com/22586369/97008029-f826fd00-154a-11eb-94e7-190ef0f6d9a6.gif)

**Comment by ugurdogrusoz** [comment]
So should we perhaps somehow move that functionality as an optional feature in this extension? In other words, if the resize to content was already done and doing it again would not change anything, we do not display the visual cue.

**Comment by msalihaltun** [comment]
I added an option to remove resize to content cue when a node is already resized to content, set to `false` by default. 

I have been looking into the resize handles locking up, it seemed somewhat random before. Now it is reproducible, when compound nodes are resized to content _even once_, their resize handles are locked.

**Comment by msalihaltun** [comment]
The locking up for compound node should be fixed now.

**Comment by hasanbalci** [comment]
It seems ok now.
