### ISSUE TITLE
Option for disabling arrow keys?

### ISSUE THREAD

**Issue by tntmarket** [iVis-at-Bilkent/cytoscape.js-node-editing#38]
Hi, can we add an option like `moveWithArrowKeys`, that disables arrow key movement when set to false?

Other apps might want to bind the arrow keys to other functions

**Comment by ugurdogrusoz** [comment]
Let's implement such an option as requested.

**Comment by msalihaltun** [comment]
Added, @hasanbalci can you test it?

**Comment by hasanbalci** [comment]
It works well.
