### ISSUE TITLE
Cannot move child node within Compound Node after resizing.

### ISSUE THREAD

**Issue by vinay-nadig-0042** [iVis-at-Bilkent/cytoscape.js-node-editing#41]
Hi,

When a compound node that has a single child get's resized, it's no longer possible to move the child node freely within the compound node. The child node becomes 'sticky' to a position within the compound node.

Could you please confirm if this is intended behavior? If yes, is there a workaround to make the child node move freely within the parent?

Here is a small video demonstrating the issue.

https://user-images.githubusercontent.com/9299876/127066055-28022d3d-6ba3-4725-8e6a-7f7b22421065.mov

Here is the modified section of demo.html file from this repository if you would like to reproduce the issue.

```
document.addEventListener('DOMContentLoaded', function(){

	var cy = window.cy = cytoscape({
		container: document.getElementById('cy'),

		style: [
			{
				selector: 'node',
				style: {
					'content': 'data(name)',
					'textValign': 'center',
					'width': '50px',
					'height': '50px'
				}
			},
			{
				selector: ':parent',
				style: {
					'textValign': 'bottom'
				}
			}
		],

		layout: { name: 'preset'},
		
		wheelSensitivity: 0.1,

		elements: {
			nodes: [
				{ data: {id: 'p', name: 'Parent'}},
				{ data: { id: 'j', parent: 'p', name: 'Child1' }, position: {x: 100, y: 100}},
				{ data: { id: 'k', name: 'Orphan1' }, position: {x: 100, y: 200} }
			]
		}
	});

	cy.nodeEditing({
		resizeToContentCueImage: 'resizeCue.svg',
		autoRemoveResizeToContentCue: true,
		isNoResizeMode: function(n) {
          return n.is(".noResizeMode")
        },
	});

	cy.on("nodeediting.resizestart", function (e, type) {
		console.log(type);
	});

	cy.on("nodeediting.resizeend", function (e, type) {
		document.body.style.cursor = 'initial';
	});

});
```

If you need any further info, please let me know.

**Comment by hasanbalci** [comment]
This is a default behaviour of Cytoscape.js. You may get a better community response for a workaround if you post your question to stackoverflow.
