### ISSUE TITLE
Usage in React

### ISSUE THREAD

**Issue by kristnr** [iVis-at-Bilkent/cytoscape.js-node-editing#42]
I would like to import this extension into React but have continually been getting TypeErrors. Is it possible to import this and if so what is the correct syntax?

**Comment by canbax** [comment]
@kristnr  What errors are you getting? Can you put some? Also, note that this extension has some dependencies like 

Cytoscape.js ^3.2.0
jquery ^1.7.0 || ^2.0.0 || ^3.0.0
konva ^7.0.3
cytoscape-undo-redo ^1.0.10 (optional)

**Comment by kristnr** [comment]
@canbax My errors are pretty simple. Mainly it has been "TypeError: cy.nodeEditing is not a function" or "TypeError: ext.apply is not a function", but as I try different ways of importing, the error fluctuates a little.

Currently, I have:
import $ from 'jquery';
import Konva from 'konva';
import cytoscape from 'cytoscape';
import CytoscapeComponent from 'react-cytoscapejs';
import nodeEditing from 'cytoscape-node-editing';
cytoscape.use(nodeEditing);

I thought about importing react-konva as well, but didn't think it was needed.

**Comment by kristnr** [comment]
Revisiting this, I found that the import instructions on the page were correct. I may have had a typo or was missing a requirement at some point prior. Here is what I have now:
import $ from 'jquery';
import cytoscape from 'cytoscape';
const konva = require('konva');
const nodeEditing = require('cytoscape-node-editing');
nodeEditing(cytoscape, $, konva);
